[package]
name = "morum-ui"
version = "0.1.0"
authors = ["Wei Tang <wei@pacna.org"]
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = "0.3"
yew = "0.19"

[build-dependencies]
build-helper = "0.1.1"